// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {casemgr} from '../models';
import {session} from '../models';
import {dbengine} from '../models';
import {config} from '../models';
import {job} from '../models';
import {report} from '../models';

export function ApprovePlan(arg1:string,arg2:string):Promise<void>;

export function CancelJob(arg1:string):Promise<void>;

export function CloseCase(arg1:string):Promise<void>;

export function CreateCase(arg1:string):Promise<casemgr.CaseInfo>;

export function CreateSession(arg1:string):Promise<session.Session>;

export function DeleteCase(arg1:string):Promise<void>;

export function DeleteReport(arg1:string,arg2:string):Promise<void>;

export function DeleteSession(arg1:string,arg2:string):Promise<void>;

export function ExecuteSQL(arg1:string,arg2:string,arg3:string):Promise<dbengine.QueryResult>;

export function ExportReport(arg1:string,arg2:string,arg3:string):Promise<void>;

export function GetConfig():Promise<config.Config>;

export function GetJobStatus(arg1:string):Promise<job.Job>;

export function GetSession(arg1:string,arg2:string):Promise<session.Session>;

export function GetTables(arg1:string):Promise<Array<dbengine.TableMeta>>;

export function ImportData(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ListCases():Promise<Array<casemgr.CaseInfo>>;

export function ListReports(arg1:string):Promise<Array<report.Report>>;

export function ListSessions(arg1:string):Promise<Array<session.Session>>;

export function OpenCase(arg1:string):Promise<void>;

export function RemoveTable(arg1:string,arg2:string):Promise<void>;

export function RenameReport(arg1:string,arg2:string,arg3:string):Promise<void>;

export function RenameSession(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ReopenSession(arg1:string,arg2:string):Promise<void>;

export function SaveConfig(arg1:config.Config):Promise<void>;

export function SendMessage(arg1:string,arg2:string,arg3:string):Promise<void>;
