// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApprovePlan(arg1, arg2) {
  return window['go']['main']['App']['ApprovePlan'](arg1, arg2);
}

export function CancelJob(arg1) {
  return window['go']['main']['App']['CancelJob'](arg1);
}

export function CloseCase(arg1) {
  return window['go']['main']['App']['CloseCase'](arg1);
}

export function CreateCase(arg1) {
  return window['go']['main']['App']['CreateCase'](arg1);
}

export function CreateSession(arg1) {
  return window['go']['main']['App']['CreateSession'](arg1);
}

export function DeleteCase(arg1) {
  return window['go']['main']['App']['DeleteCase'](arg1);
}

export function ExecuteSQL(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExecuteSQL'](arg1, arg2, arg3);
}

export function ExportReport(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExportReport'](arg1, arg2, arg3);
}

export function FinalizeSession(arg1, arg2) {
  return window['go']['main']['App']['FinalizeSession'](arg1, arg2);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetJobStatus(arg1) {
  return window['go']['main']['App']['GetJobStatus'](arg1);
}

export function GetSession(arg1, arg2) {
  return window['go']['main']['App']['GetSession'](arg1, arg2);
}

export function GetTables(arg1) {
  return window['go']['main']['App']['GetTables'](arg1);
}

export function ImportData(arg1, arg2, arg3) {
  return window['go']['main']['App']['ImportData'](arg1, arg2, arg3);
}

export function ListCases() {
  return window['go']['main']['App']['ListCases']();
}

export function ListReports(arg1) {
  return window['go']['main']['App']['ListReports'](arg1);
}

export function ListSessions(arg1) {
  return window['go']['main']['App']['ListSessions'](arg1);
}

export function OpenCase(arg1) {
  return window['go']['main']['App']['OpenCase'](arg1);
}

export function RemoveTable(arg1, arg2) {
  return window['go']['main']['App']['RemoveTable'](arg1, arg2);
}

export function RequestAdditionalAnalysis(arg1, arg2) {
  return window['go']['main']['App']['RequestAdditionalAnalysis'](arg1, arg2);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SendMessage(arg1, arg2, arg3) {
  return window['go']['main']['App']['SendMessage'](arg1, arg2, arg3);
}
